### ISSUE TITLE
Input format: should be a standard ? Why not InToHyLo ?

### ISSUE THREAD

**Issue by Mystelven** [Meleagant/MOLOSS#1]
Hello, 

It is not really an issue but more a proposition of a feature. If you want this solver to be used in comparison with others solvers, it is worth it to standardize the input.

Here is the BNF grammar of the most used input standard (see [[4.1, 1]](http://cs.ru.nl/paar16/paper-07.pdf) for more details):

    <file> ::= 'begin' <fml> 'end'
    
    <fml>  ::= '(' <fml> ')'
        |   'true' | 'false' 
        |   'p'<id> 
        |   '~' <fml>
        |   '<r' <id> '>' <fml> 
        |   '[r' <id> ']' <fml> 
        |   <fml> '&' <fml>
        |   <fml> '|' <fml>
        |   <fml> '->' <fml>
        |   <fml> '<->' <fml>

with `<id>` being a numerical sequence. Unary operators have the highest precedence in this format (called InToHyLo). The precedence of the binary operators is the following: `&`, `|`, `->`, `<->`.
 
If you want to just patch your solver and not deal fully with the multiple modalities, you can just parse `[]` by `[r1]` and `<>` by `<r1>`.

Keep me informed if you plan to do such modifications, if not, I will try to propose a pull-request in the following weeks in order to see the performance of such a solver on real instances where SMT solving has more chances to be efficient.

Best Regards,

**Comment by tofgarion** [comment]
Hello Valentin,

Sorry for the late response. This is indeed a good idea, implementing it requires some work though: the current "bml" format used by Josselin specifies the frame axioms (following the TANCS2000 benchmarks format used by Spass), and we should pass the axioms to be used as command line arguments for instance. I have anyway planned to refactor the command line interface of MOLOSS, so this is a good excuse to finally work on it ;)

Best,

Christophe

**Comment by Mystelven** [comment]
Hello Christophe,

Yep, I think it would be nice to have some arguments to deal with the different axioms. It is nicer to have the problems encoded independently of the logic they are solved with. 

In such way, each benchmark can be re-used to evaluate different modal logic * solvers. 
Keep me informed when the refactoring will be done. I am looking forward seeing the performance of an SMT-based solver on the different modal logic benchmarks. 

Best Regards,

**Comment by Meleagant** [comment]
Hello,

Sorry for the late response. I already made a major refactoring of the code : Now decision procedures are in a module. I'll try to push it this evening, with the refactoring of the command line of moloss.

**Comment by Mystelven** [comment]
Hello Josselin,

I got an eye on this repository. Just closed this issue when Moloss can read the InToHyLo format and can deal with arguments with the different axioms. :)

Best Regards.

**Comment by Meleagant** [comment]
Hello Valentin, 
I reopen this issue because there are still a question with DIMACS CNF standard : 
If the value of a propositional doesn't change the satisfiability of a model, do we have to print it ?

Best regards,

**Comment by Mystelven** [comment]
You mean the 'FKM' (Flat Kripke Model format) in Sec. 4.2. to output the model ? (DIMACS CNF is the inspiration of it and it is the standard input for SAT solver).

Well it is not necessary. But it will be considered as false by the checker if it does not exist.
Let us give an example of a FKM model:

    2 3 1 2
    2 0
    1 2 0
    0
    r1 w0 w1
    r1 w1 w2

it will be interpreted as the following Kripke model:

    (~p1 p2) -> (p1 p2) -> (~p1 ~p2)
      w0          w1          w2

I hope it is clear :)

**Comment by Mystelven** [comment]
I just run Moloss on the example you gave in the data/folder.
And it outputs the following:

    valentinmontmirail@Ubuntu:$ ./moloss.byte ./data/InToHyLo/test.InToHyLo --get-model
    2 1 1 1
    1 -2 0
    1 -2 0
    r1 w0 w1
    c SAT

So that's perfect, I would just advised to output as follows: 

    valentinmontmirail@Ubuntu:$ ./moloss.byte ./data/InToHyLo/test.InToHyLo --get-model
    s SATISFIABLE
    v 2 1 1 1
    v 1 -2 0
    v 1 -2 0
    v r1 w0 w1

Which is then, exactly what the Checker (http://www.cril.univ-artois.fr/~montmirail/mdk-verifier/) is reading (and what the other solvers are outputting also, in case of a future 'competition')

**Comment by Meleagant** [comment]
There is a problem I don't know how to solve : when printing the model the satisfiability is printed after the model despite the code and the `flush_all`.

**Comment by Mystelven** [comment]
Nevermind. One can just make the solver output the model and then use a small script to modify the display and run the checker offline. So that's okay :).
