### ISSUE TITLE
Problem with installation in the file `ast_fo`

### ISSUE THREAD

**Issue by Mystelven** [Meleagant/MOLOSS#2]
There is a problem with the installation.
Installing Opam, Ocaml and everything is ok.

But then when I type `make` here is the following problem:

    valentinmontmirail@Ubuntu:~/moloss/$ make
    ocamlfind query unix
    /usr/lib/ocaml

    ocamlfind query minisat
    /home/valentinmontmirail/.opam/system/lib/minisat

    ocamlfind query msat
    /home/valentinmontmirail/.opam/system/lib/msat

    ocamlbuild -use-ocamlfind -I src -I tests src/moloss.native
    Warning: tag "color" does not expect a parameter, but is used with parameter "always"
    + ocamlfind ocamlc -c -bin-annot -package minisat -package unix -package msat -I src -I tests -o 
    src/ast_fo.cmo src/ast_fo.ml
    File "src/ast_fo.ml", line 65, characters 29-41:
    Error: Unbound value Sset.of_list

    Command exited with code 2.

It looks like there is a problem in this file "src/ast_fo.ml", line 65, characters 29-41.

**Comment by Meleagant** [comment]
Are you sure you are using a correct version of OCaml ? You need a version >= 4.05. (The function `of_list` exists since 4.02)

**Comment by Mystelven** [comment]
Yep that was the problem thanks :) it is fixed now and it compiles and solves InToHyLo problems.

You should maybe indicate in your readme that one should do `eval $(opam config env)`  between the installation of the packages and calling make to compile the solver. :)
