### ISSUE TITLE
Could you make a release ?

### ISSUE THREAD

**Issue by Mystelven** [Meleagant/MOLOSS#6]
Hello, 

I will use Moloss in an article, but to cite it, I need something that can not change during the time.
It would be nice to have a release like Moloss 1.0. Like this, if someone is not sure about the results we give in the paper, he can download moloss 1.0, which will be the exact same version as the one we use, and re-run the solver on the benchmarks considered. 

Thanks in advance,

**Comment by tofgarion** [comment]
Hello,

I have just created a v0.9 release.
